# -*- coding: utf-8 -*-
"""Generates Source/PostalPlaces.inc from the GeoNames Canadian postal file.

Run when the dataset is refreshed:

    curl -o CA.zip https://download.geonames.org/export/zip/CA.zip
    unzip CA.zip
    python Source/Tools/gen_postal_places.py CA.txt

Canada Post's own postal-code database is proprietary and its lookup API is a
paid product whose licence does not allow redistributing the data inside an
application, so it is not an option here. GeoNames publishes the Canadian file
under CC BY 4.0, which is, with attribution.

The dataset is forward-sortation-area level -- the first three characters -- and
its place names are postal-sector labels rather than city names: "Longueuil
Southeast", "Sorel Central", "Downtown Toronto (CN Tower / King and Spadina /
...)". Both the compass suffix and the parenthetical list are stripped here, at
generation time, so the runtime lookup is a plain binary search.
"""
import io
import re
import sys

DIRECTIONS = ("Northeast", "Northwest", "Southeast", "Southwest",
              "North", "South", "East", "West",
              "Central", "Inner", "Outer")

PARENTHETICAL = re.compile(r"\s*\([^)]*\)\s*$")


def clean(name):
    """'Longueuil Southeast' -> 'Longueuil'; 'Eastern Alberta (St. Paul)' -> 'Eastern Alberta'."""
    name = PARENTHETICAL.sub("", name).strip()

    for direction in DIRECTIONS:
        if name.endswith(" " + direction):
            candidate = name[: -len(direction) - 1].strip()
            # Never strip a name down to nothing: some sectors are named only
            # for their direction.
            if candidate:
                name = candidate
            break

    return name


def escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main(source, target):
    places = {}
    for line in io.open(source, encoding="utf-8"):
        parts = line.rstrip("\n").split("\t")
        if len(parts) < 5:
            continue

        fsa, name, province = parts[1].strip(), clean(parts[2]), parts[4].strip()
        if len(fsa) != 3 or not name or not province:
            continue

        places.setdefault(fsa, (name, province))

    out = io.open(target, "w", encoding="utf-8", newline="\n")
    out.write("// Generated by Source/Tools/gen_postal_places.py -- do not edit by hand.\n")
    out.write("//\n")
    out.write("// Canadian forward sortation areas (the first three characters of a postal\n")
    out.write("// code) and the place each one covers. Sorted by code so the lookup can be a\n")
    out.write("// binary search.\n")
    out.write("//\n")
    out.write("// Source: GeoNames postal-code data, https://download.geonames.org/export/zip/\n")
    out.write("// Licensed CC BY 4.0. Attribution belongs in the application's about screen.\n")
    out.write("//\n")
    out.write("// %d entries.\n\n" % len(places))

    for fsa in sorted(places):
        name, province = places[fsa]
        out.write('    { "%s", "%s", "%s" },\n' % (fsa, escape(name), province))

    out.close()
    print("wrote %s (%d entries)" % (target, len(places)))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "CA.txt",
         sys.argv[2] if len(sys.argv) > 2 else "PostalPlaces.inc")
